[package]
name = "update_telemetry_reporter"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
ureq = { version = "2.10.1", features = ["json"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
glean = "62.0.0"
flate2 = "1.0.34"
tempfile = "3.14.0"
env_logger = { version = "0.10.0", default-features = false, features = ["humantime"] }

[build-dependencies]
glean-build = { git = "https://github.com/mozilla/glean" }
